appearance:
  default_theme: system
  show_theme_switcher: true

deployment:
  basePath: /demo_warehouse

plugins:
  components:
    "@evidence-dev/core-components": {}
  datasources:
    "@evidence-dev/databricks": {}
